# Generated by Django 5.2.17 on 2026-09-09 15:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='Write in Markdown!')),
                ('proficiency', models.CharField(choices=[('beginner', 'Beginner'), ('experienced', 'Experienced'), ('advanced', 'Advanced')], default='experienced', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, null=True)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, help_text='Write in Markdown!')),
                ('skills', models.ManyToManyField(related_name='projects', to='main.skill')),
            ],
        ),
    ]
