# Generated by Django 5.2.17 on 2026-09-15 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_experience_started_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='thumbnail',
            field=models.URLField(blank=True, help_text='16:9 pls', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.URLField(blank=True, help_text='16:9 pls', null=True),
        ),
    ]
